# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "kt-albert-stock-notification-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "/Users/mac/Projects/Personal/albert_product_casestudy_8.29.24/django/core/lambda/kt-albert-stock-notification-app/template.yaml"
s3_bucket = "aws-sam-cli-managed-kt-albe-artifactsloggingbucket-aebeivm59zkz"
stack_name = "aws-sam-cli-managed-kt-albert-stock-notification-app-stage1-pipeline-resources"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
